import type { Theme } from "@/types/theme";

export const themes: Theme[] = [
  {
    id: "futebol-2026",
    name: "Futebol 2026",
    description: "Vire a lenda do campo. Cards no estilo Copa do Mundo com seus dados de jogador.",
    badge: "Popular",
    icon: "⚽",
    gradient: "from-green-600 to-yellow-500",
    bgColor: "#064E3B",
    fields: [
      { key: "nome", label: "Nome do Jogador", type: "text", placeholder: "Seu nome completo", required: true },
      { key: "genero", label: "Gênero", type: "select", options: ["Feminino", "Masculino"], required: true },
      { key: "pais", label: "País", type: "text", placeholder: "Brasil", required: true },
      { key: "time", label: "Time", type: "text", placeholder: "Nome do seu time", required: true },
      { key: "dataNascimento", label: "Data de Nascimento", type: "date", required: true },
      { key: "altura", label: "Altura (cm)", type: "number", placeholder: "175", required: true },
      { key: "peso", label: "Peso (kg)", type: "number", placeholder: "70", required: true },
      { key: "posicao", label: "Posição", type: "select", options: ["Goleiro", "Lateral", "Zagueiro", "Volante", "Meia", "Atacante", "Centroavante"], required: true },
    ],
  },
  {
    id: "futebol-panini",
    name: "Futebol Panini",
    description: "Estilo clássico de figurinha Panini. Background turquoise com dados do jogador.",
    badge: "Novo",
    icon: "🏆",
    gradient: "from-teal-600 to-cyan-700",
    bgColor: "#00B4A6",
    fields: [
      { key: "nome", label: "Nome do Jogador", type: "text", placeholder: "Seu nome completo", required: true },
      { key: "genero", label: "Gênero", type: "select", options: ["Feminino", "Masculino"], required: true },
      { key: "pais", label: "País", type: "text", placeholder: "Brasil", required: true },
      { key: "time", label: "Time", type: "text", placeholder: "Nome do seu time", required: true },
      { key: "dataNascimento", label: "Data de Nascimento", type: "date", required: true },
      { key: "altura", label: "Altura (cm)", type: "number", placeholder: "175", required: true },
      { key: "peso", label: "Peso (kg)", type: "number", placeholder: "70", required: true },
      { key: "posicao", label: "Posição", type: "select", options: ["Goleiro", "Lateral", "Zagueiro", "Volante", "Meia", "Atacante", "Centroavante"], required: true },
    ],
  },
  {
    id: "futebol-familia",
    name: "Futebol Família",
    description: "Reúna toda a família em uma imagem épica LANDSCAPE no campo de futebol. Envie fotos de cada membro.",
    badge: "Novo",
    icon: "👨‍👩‍👧‍👦",
    gradient: "from-green-500 to-yellow-400",
    bgColor: "#047857",
    fields: [
      { key: "nomeFamilia", label: "Nome da Família", type: "text", placeholder: "Família Silva", required: true },
      { key: "quantidadeMembros", label: "Quantidade de Membros", type: "number", placeholder: "4", required: true },
      { key: "pais", label: "País", type: "text", placeholder: "Brasil", required: true },
      { key: "time", label: "Time do Coração", type: "text", placeholder: "Seleção Brasileira", required: true },
    ],
  },
  {
    id: "hero-card",
    name: "Hero Card",
    description: "Seja o herói épico que você sempre foi. Cards de fantasia com poderes únicos.",
    badge: "Popular",
    icon: "⚔️",
    gradient: "from-purple-700 to-indigo-900",
    bgColor: "#1E1B4B",
    fields: [
      { key: "nome", label: "Nome do Herói", type: "text", placeholder: "Seu nome heroico", required: true },
      { key: "classe", label: "Classe", type: "select", options: ["Guerreiro", "Mago", "Arqueiro", "Paladino", "Assassino", "Druida", "Necromante"], required: true },
      { key: "poderPrincipal", label: "Poder Principal", type: "text", placeholder: "Ex: Chama Eterna", required: true },
      { key: "fraseCurta", label: "Frase de Batalha", type: "text", placeholder: "Uma frase épica sua", required: true },
      { key: "raridade", label: "Raridade", type: "select", options: ["Comum", "Raro", "Épico", "Lendário", "Mítico"], required: true },
    ],
  },
  {
    id: "profissional-premium",
    name: "Profissional Premium",
    description: "Seu perfil profissional em formato de card premium. Perfeito para networking.",
    badge: "Novo",
    icon: "💼",
    gradient: "from-slate-700 to-blue-900",
    bgColor: "#1E293B",
    fields: [
      { key: "nome", label: "Nome Completo", type: "text", placeholder: "Seu nome profissional", required: true },
      { key: "cargo", label: "Cargo", type: "text", placeholder: "CEO, Desenvolvedor, Designer...", required: true },
      { key: "especialidade", label: "Especialidade", type: "text", placeholder: "Sua principal habilidade", required: true },
      { key: "stackPrincipal", label: "Stack / Ferramentas", type: "text", placeholder: "React, Python, Figma...", required: true },
      { key: "fraseProfissional", label: "Frase Profissional", type: "text", placeholder: "Seu lema profissional", required: true },
    ],
  },
  {
    id: "reino-medieval",
    name: "Reino Medieval",
    description: "Entre nos reinos de fantasia. Seja cavaleiro, rei ou feiticeiro em cards épicos.",
    badge: "Premium",
    icon: "🏰",
    gradient: "from-amber-700 to-red-900",
    bgColor: "#431407",
    fields: [
      { key: "nome", label: "Nome do Personagem", type: "text", placeholder: "Seu nome medieval", required: true },
      { key: "reino", label: "Reino", type: "text", placeholder: "Nome do seu reino", required: true },
      { key: "classe", label: "Classe", type: "select", options: ["Cavaleiro", "Rei/Rainha", "Feiticeiro", "Bardo", "Paladino", "Ranger", "Ladrão"], required: true },
      { key: "arma", label: "Arma Principal", type: "text", placeholder: "Espada Flamejante...", required: true },
      { key: "poder", label: "Poder Especial", type: "text", placeholder: "Seu poder único", required: true },
    ],
  },
  {
    id: "escola-de-magia",
    name: "Escola de Magia",
    description: "Ingresse na escola de magia mais épica do mundo. Seu card de estudante mágico.",
    badge: "Popular",
    icon: "🪄",
    gradient: "from-violet-700 to-fuchsia-900",
    bgColor: "#2E1065",
    fields: [
      { key: "nome", label: "Nome do Mago", type: "text", placeholder: "Seu nome mágico", required: true },
      { key: "casaFicticia", label: "Casa Mágica", type: "select", options: ["Casa da Chama", "Casa da Sombra", "Casa da Luz", "Casa do Vento", "Casa da Terra", "Casa das Águas"], required: true },
      { key: "poder", label: "Poder Mágico", type: "text", placeholder: "Teletransporte, Piromancia...", required: true },
      { key: "animalGuia", label: "Animal Guia", type: "text", placeholder: "Coruja, Dragão, Fênix...", required: true },
      { key: "nivelMagico", label: "Nível Mágico", type: "select", options: ["Aprendiz", "Iniciado", "Praticante", "Mago", "Arquimago", "Grande Mestre"], required: true },
    ],
  },
  {
    id: "baby-hero",
    name: "Baby Hero",
    description: "Transforme seu filho em um super-herói. Cards fofos e épicos para crianças.",
    badge: "Família",
    icon: "🦸",
    gradient: "from-pink-500 to-orange-400",
    bgColor: "#4C0519",
    fields: [
      { key: "nomeCrianca", label: "Nome da Criança", type: "text", placeholder: "Nome do pequenininho", required: true },
      { key: "idade", label: "Idade", type: "number", placeholder: "5", required: true },
      { key: "poderFofo", label: "Superpoder Fofo", type: "text", placeholder: "Raio de Abraço, Sorriso Mágico...", required: true },
      { key: "fraseCurta", label: "Frase da Criança", type: "text", placeholder: "Uma frase característica", required: true },
    ],
  },
  {
    id: "family-pack",
    name: "Family Pack",
    description: "Um card épico para toda a família. Mostre a força da sua equipe mais especial.",
    badge: "Família",
    icon: "👨‍👩‍👧‍👦",
    gradient: "from-teal-600 to-cyan-800",
    bgColor: "#0F3460",
    fields: [
      { key: "nomeFamilia", label: "Nome da Família", type: "text", placeholder: "Família Silva, Família Souza...", required: true },
      { key: "membrosFamilia", label: "Membros da Família", type: "text", placeholder: "Ex: Pai, Mãe, João (8), Maria (5)", required: true },
      { key: "fraseFamilia", label: "Lema da Família", type: "text", placeholder: "Nossa força é o amor", required: true },
      { key: "ano", label: "Ano", type: "number", placeholder: "2026", required: true },
    ],
  },
  {
    id: "pet-star",
    name: "Pet Star",
    description: "Seu pet merece ser uma estrela! Cards épicos para os melhores amigos.",
    badge: "Novo",
    icon: "🐾",
    gradient: "from-yellow-600 to-orange-700",
    bgColor: "#431407",
    fields: [
      { key: "nomePet", label: "Nome do Pet", type: "text", placeholder: "Rex, Fofinha, Bolinha...", required: true },
      { key: "tipo", label: "Tipo de Pet", type: "select", options: ["Cachorro", "Gato", "Pássaro", "Coelho", "Hamster", "Peixe", "Réptil", "Outro"], required: true },
      { key: "personalidade", label: "Personalidade", type: "text", placeholder: "Brincalhão, Carinhoso, Preguiçoso...", required: true },
      { key: "poderFicticio", label: "Superpoder Fictício", type: "text", placeholder: "Latido Trovejante, Ronronar Hipnótico...", required: true },
    ],
  },
  {
    id: "battle-card",
    name: "Battle Card",
    description: "Desafie seu rival! Cards épicos de batalha face a face para jogos e apostas.",
    badge: "Novo",
    icon: "⚡",
    gradient: "from-red-700 to-orange-600",
    bgColor: "#7F1D1D",
    fields: [
      { key: "nomeJogador1", label: "Seu Nome", type: "text", placeholder: "Seu nome de batalha", required: true },
      { key: "nomeRival", label: "Nome do Rival", type: "text", placeholder: "Nome do seu desafiante", required: true },
      { key: "estiloBatalha", label: "Estilo de Batalha", type: "select", options: ["Força Bruta", "Magia Sombria", "Velocidade Relâmpago", "Defesa Absoluta", "Malandragem Tática"], required: true },
      { key: "poderPrincipal", label: "Poder Principal", type: "text", placeholder: "Golpe Devastador...", required: true },
    ],
  },
  {
    id: "avatar-poster",
    name: "Avatar / Pôster",
    description: "Crie seu avatar cinemático ou pôster épico para redes sociais e impressão.",
    badge: "Premium",
    icon: "🎬",
    gradient: "from-gray-700 to-blue-900",
    bgColor: "#0F172A",
    fields: [
      { key: "nome", label: "Seu Nome", type: "text", placeholder: "Seu nome artístico", required: true },
      { key: "estiloVisual", label: "Estilo Visual", type: "select", options: ["Cyberpunk", "Fantasia épica", "Sci-Fi", "Noir cinematográfico", "Samurai", "Mitologia Nórdica", "Super-herói"], required: true },
      { key: "fraseCurta", label: "Frase Icônica", type: "text", placeholder: "Sua frase de identidade", required: true },
      { key: "energiaPrincipal", label: "Energia Principal", type: "select", options: ["Fogo", "Gelo", "Raio", "Sombra", "Luz", "Vento", "Terra"], required: true },
    ],
  },
];

export function getThemeById(id: string): Theme | undefined {
  return themes.find((t) => t.id === id);
}

export function getThemeBySlug(slug: string): Theme | undefined {
  return themes.find((t) => t.id === slug);
}
